"""Add options to question model

Revision ID: 08f5071a5eb7
Revises: 7cfaa7eaf6f7
Create Date: 2026-04-03 15:20:43.004781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f5071a5eb7'
down_revision: Union[str, Sequence[str], None] = '7cfaa7eaf6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('options', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'options')
    # ### end Alembic commands ###
